name: CD

on:
  push:
    branches:
      - main
    paths:
      - "**/Dockerfile"
      - ".github/workflows/cd.yml"

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/${{ github.repository_owner }}/nix

jobs:
  push-docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        version: ["2.17.0"]
        variant: [ubuntu]

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          context: .
          file: ./${{ matrix.variant }}/Dockerfile
          build-args: |
            NIX_VERSION=${{ matrix.version }}
          tags: ${{ env.IMAGE }}:${{ matrix.version }}-${{ matrix.variant }}
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:${{ matrix.version }}-${{ matrix.variant }}
          cache-to: type=inline

      - name: Test for nix version
        run: |
          image_nix_version=$(docker run --rm ${{ env.IMAGE }}:${{ matrix.version }}-${{ matrix.variant }} nix eval --raw --expr builtins.nixVersion)
          echo "Expected: \"${{ matrix.version }}\", Got: \"${image_nix_version}\""
          [ "${image_nix_version}" == "${{ matrix.version }}" ]
